# Generated by Django 3.2.3 on 2021-06-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_VAT_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('min_quantity', models.IntegerField()),
                ('max_quantity', models.IntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
