# Generated by Django 3.2.3 on 2021-06-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOnCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('REC', 'Recibido'), ('SENT', 'Enviado'), ('WAIT', 'En espera')], default='WAIT', max_length=10)),
                ('max_payment_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
            ],
        ),
    ]
