version: '3.9'

services:
  db:
    container_name: 'db'
    image: postgres:latest
    ports:
    - 54320:5432
    env_file:
      - .env

#    volumes:
#    - db_data:/var/lib/postgresql/data

  web:
    build: .
    tty: true
    container_name: 'back'
    ports:
    - 8000:8000
    volumes:
    - ./app:/code/app
    entrypoint: ['bash', 'entrypoint.sh']
    depends_on:
      - db

volumes:
  db_data: