# Generated by Django 3.2.3 on 2021-06-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Packaging', 'Packaging'), ('Sent', 'Sent'), ('Delivered', 'Delivered')], default='Packaging', max_length=20)),
                ('bill', models.IntegerField()),
            ],
        ),
    ]
