# Generated by Django 3.2.3 on 2021-07-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pack', 'Empacando'), ('Sent', 'Enviado'), ('Del', 'Entregado')], default='Pack', max_length=20),
        ),
    ]
