# Generated by Django 3.2.3 on 2021-07-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Packaging', 'Packaging'), ('Sent', 'Sent'), ('Delivered', 'Delivered')], default='Packaging', max_length=20),
        ),
    ]
