# Generated by Django 3.2.3 on 2021-06-01 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_card', models.BigIntegerField()),
                ('user_fist_name', models.CharField(max_length=100)),
                ('user_last_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('employee_type', models.CharField(choices=[('Conveyor', 'Transportador'), ('Seller', 'Vendedor'), ('Accountant', 'Contador')], default='Accountant', max_length=20)),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card', models.BigIntegerField(unique=True)),
                ('cellphone', models.BigIntegerField()),
                ('city', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Conveyor', 'Transportador'), ('Seller', 'Vendedor'), ('Accountant', 'Contador')], default='Accountant', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
