# Generated by Django 3.2.3 on 2021-06-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmployee',
        ),
    ]
