# Generated by Django 3.2.3 on 2021-08-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20210801_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='value',
        ),
    ]
