# Generated by Django 3.2.3 on 2021-06-15 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('deliver_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=100)),
                ('state', models.CharField(choices=[('Wait', 'En espera'), ('Packaging', 'Empacando'), ('Sent', 'Enviado'), ('Delivered', 'Entregado')], default='Wait', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
    ]
