# Generated by Django 3.2.3 on 2021-06-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('seller', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('max_deliver_date', models.DateField()),
                ('state', models.CharField(choices=[('Wait', 'Wait'), ('Packaging', 'Packaging'), ('Sent', 'Sent'), ('Delivered', 'Delivered')], default='Wait', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.client')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
