# Generated by Django 3.2.3 on 2021-07-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedproduct',
            unique_together={('order', 'product')},
        ),
    ]
