# Generated by Django 3.2.3 on 2021-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderedproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('Wait', 'Wait'), ('Packaging', 'Packaging'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Wait', max_length=15),
        ),
    ]
